---
abstract: 'return a windowed slice of the array'
author:
  - 'Written by Mark Fowler <mark@twoshortplanks.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Array-Windowed
no_index:
  directory:
    - inc
    - t
    - xt
resources:
  homepage: https://github.com/2shortplanks/Array-Windowed/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/2shortplanks/Array-Windowed.git
    web: https://github.com/2shortplanks/Array-Windowed/tree
version: 1.00
